frontend/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'frontend'

urlpatterns = [
    path('', index, name='index'),
    path('detail/<int:id>/', TrekDetail, name='detail'),
    #banner
    path('banners/', BannerImages, name='banner'),
    path('add-banner/', AddBannerImages, name='add_banner'),
    path('view-banner/<int:id>/', ViewBanners, name='view_banner'),
    path('edit-banner/<int:id>/', EditBanner, name='edit_banner'),
    path('delete-banner/<int:id>/', DeleteBanner, name='delete_banner'),
    path('activate-deactive-banner/<int:id>/', ActivatDeactivateBanner, name='activate_deactivate_banner'),
    #State
    path('state-list/',StateList, name='state_list'),
    path('state-detail/<int:id>/',StateDetail, name='state_detail'),
    path('add-state/', AddState, name='add_state'),
    path('view-state/<int:id>/', ViewState, name='view_state'),
    path('edit-state/<int:id>/', EditState, name='edit_state'),
    path('delete-state/<int:id>/', DeleteState, name='delete_state'),
    path('activate-deactivate-state/<int:id>/', ActivatDeactivateState, name='activate_deactivate_state'),

    #district
    path('district-list/',DistrictList, name='district_list'),
    path('district-detail/<int:id>/',DistrictDetail, name='district_detail'),
    path('add-district/', AddDistrict, name='add_district'),
    path('view-district/<int:id>/', ViewDistrict, name='view_district'),
    path('edit-district/<int:id>/', EditDistrict, name='edit_district'),
    path('delete-district/<int:id>/', DeleteDistrict, name='delete_district'),
    #Tresks
    path('trek-list/',TrekList, name='trek_list'),
    path('add-trek/', AddTrek, name='add_trek'),
    path('view-trek/<int:id>/', ViewTrek, name='view_trek'),
    path('edit-trek/<int:id>/', EditTrek, name='edit_trek'),
    path('delete-trek/<int:id>/', DeleteTrek, name='delete_trek'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  url
from accounts.views import AdminLoginView


urlpatterns = [
    url(r'^admin/login/', AdminLoginView.as_view()),
    # path('index/', index, name='index'),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls',namespace='user')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    # path('store/', include('store.urls',namespace='store')),
    path('', include('frontend.urls',namespace='frontend')),
    path('loggers/', include('logger.urls',namespace='loggers')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

app_name = 'users'

urlpatterns = [
    path('users-list/', UserList, name='users_list'),
]

templates/frontend_includes/footer.html
{% comment %} 
<footer>
  <div class="copyright-footer-befor-login">
      <p class="mb-0 text-center">Copyright <span id="full_year"></span> | MountCraves. All right reserved.    
          <a class="ml-2" href="/terms-and-conditions/">Terms &amp; Conditions</a> | <a href="/privacy-policy/">Privacy Policy</a>
      </p>
  </div>
</footer>
</div>

<script src="/static/admin-assets/js/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.js"></script>
<script src="/static/admin-assets/js/feather.min.js"></script>
<script src="/static/admin-assets/js/jquery.slimscroll.min.js"></script>
<script src="/static/admin-assets/js/jquery.dataTables.min.js"></script>
<script src="/static/admin-assets/js/dataTables.bootstrap4.min.js"></script>
<script src="/static/admin-assets/js/bootstrap.bundle.min.js"></script>
<script src="/static/admin-assets/js/apexcharts.min.js"></script>
<script src="/static/admin-assets/js/script.js"></script>
<script src="/static/admin-assets/js/validate.js"></script>
<script src="/static/admin-assets/js/additional-methods.min.js"></script>
<script>
  $(document).ready( function () {
      $('#full_year').text(new Date().getFullYear());
  });
  function Loader(formID) {
      if ($('#'+formID).length){
          if ($('#'+formID).valid()){
              $('body').append('<div id="loading"><i class="fas fa-spinner"></i></div>');
              $('body').css('pointer-events','none');
              $('.btn').css('pointer-events','none');
          }
      }else{
          $('body').append('<div id="loading"><i class="fas fa-spinner"></i></div>');
          $('body').css('pointer-events','none');
          $('.btn').css('pointer-events','none');
      }
  }
</script>
</body>
</html> {% endcomment %}
{% load static %}
<footer>
    <div class="wrap-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="copyright">Copyright &copy; Your Website <br/>Designed by <a href="https://www.Zerotheme.com">Zerotheme</a></div>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer -->



<!-- jQuery -->
<script src="{% static 'frontend-assets/js/jquery-2.1.1.js' %}"></script>


<!-- Bootstrap Core JavaScript -->
<script src="{% static 'frontend-assets/js/bootstrap.min.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'frontend-assets/js/agency.js' %}"></script>

<!-- Animated Top -->
<script src="{% static 'frontend-assets/js/jquery.easing.min.js' %}"></script>
<script src="{% static 'frontend-assets/js/classie.js' %}"></script>
<script src="{% static 'frontend-assets/js/cbpAnimatedHeader.js' %}"></script>

<!-- Include all compiled plugins (below), or include individual files as needed --> 
{% comment %} <script type="text/javascript" src="{% static 'frontend-assets/js/SmoothScroll.js' %}"></script> 
<script type="text/javascript" src="{% static 'frontend-assets/js/wow.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'frontend-assets/js/jquery.isotope.js' %}"></script> 
<script type="text/javascript" src="{% static 'frontend-assets/js/main.js' %}"></script> {% endcomment %}

<script>
    $(function() {
        $('#nav-wrapper').height($("#nav").height());
        
        $('#nav').affix({
            offset: { top: $('#nav').offset().top }
        });
    });
</script>

<!-- carousel -->
<script src="{%  static 'frontend-assets/owl-carousel/owl.carousel.js' %}"></script>
<script>
$(document).ready(function() {
  $("#owl-brand").owlCarousel({
    autoPlay: 3000,
    items : 1,
    itemsDesktop : [1199,1],
    itemsDesktopSmall : [979,2],
    navigation: false,
  });
});
</script>

<!-- Google Map -->
<script>
    $('.maps').click(function () {
    $('.maps iframe').css("pointer-events", "auto");
});

$( ".maps" ).mouseleave(function() {
  $('.maps iframe').css("pointer-events", "none"); 
});
</script>

</body>
</html>

templates/frontend_includes/header.html
{% comment %} 



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="description" content="POS - Bootstrap Admin Template">
    <meta name="keywords"
        content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
    <meta name="author" content="Dreamguys - Bootstrap Admin Template">
    <meta name="robots" content="noindex, nofollow">
    <title>MountCraves</title>
    <link rel="shortcut icon" href="/static/admin-assets/images/favicon.ico" />
    <link rel="stylesheet" href="/static/admin-assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/admin-assets/css/animate.css">
    <link rel="stylesheet" href="/static/admin-assets/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/static/admin-assets/css/all.min.css">
    <link rel="stylesheet" href="/static/admin-assets/css/style.css">
    <link rel="stylesheet" href="/static/admin-assets/css/style.css">
    <link rel="stylesheet" href="/static/admin-assets/css/flash.css">
    <link rel="stylesheet" href="/static/admin-assets/font-family/sf-ui-display/stylesheet.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.css">
    <link rel="stylesheet" href="https://codepen.io/fancyapps/pen/Kxdwjj.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
</head>

<body> {% endcomment %}



    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Free Bootstrap Themes by Zerotheme dot com - Free Responsive Html5 Templates">
        <meta name="author" content="https://www.Zerotheme.com">
        
        <title>TravelClub | Zerotheme.com</title>
        
        <!-- Bootstrap Core CSS -->
        <link href="{% static 'frontend-assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        
        <!-- Custom CSS -->
        <link href="{% static 'frontend-assets/css/style.css' %}" rel="stylesheet">
        
        <!-- Custom Fonts -->
        <link href="{% static 'frontend-assets/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        
        <!-- Owl Carousel Assets -->
        <link href="{% static 'frontend-assets/owl-carousel/owl.carousel.css' %}" rel="stylesheet">
        <link href="{% static 'frontend-assets/owl-carousel/owl.theme.css' %}" rel="stylesheet">
        
        <!-- jQuery and Modernizr-->
        <script src="{% static 'frontend-assets/js/jquery-2.1.1.js' %}"></script>
        {% comment %} <link rel="stylesheet" href="{% static 'frontend-assets/css/style_new.css' %}"> {% endcomment %}
	<link rel="stylesheet" type="text/css" href="{% static 'frontend-assets/css/animate.min.css' %}">
        {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"></script> {% endcomment %}
    
    </head>
    
    
    <style>
        .dropdown{
            display:inline-block; 
            position:relative;
          }
        
          .dropdown button{
            border:none;
            padding:12px  16px;
            background-color: #29282E;
            color:#fff;
            transition:.3s;
            cursor:pointer;
          }
          .dropdown button:hover{
            color: #fff;
            background-color: #7F9A00;
          }
          
          {% comment %} .dropdown:hover button{
            background-color:#29282E;
          } {% endcomment %}
        .dropdown:hover{
          filter:drop-shadow(0 2px 4px rgba(0,0,0,0.2));
        }
          .dropdown > div{
            background-color:#fff;
            z-index:1;
            visibility:hidden;
            position:absolute;
            min-width:100%;
            opacity:0;
            transition:.3s;
          }
        .dropdown .submenu{
          position:relative;
          width: 210px;
        }
         .dropdown .submenu > div{
           background-color:#fff;
          visibility:hidden;
           position:absolute;
           left:100%;
           top:0;
           transition:.3s;
           opacity:0;
        }
        /*use the following commented class if you wanna show submenu at left*/
        /*
        .dropdown .submenu.atLeft > div{
          left:-100%;
        }
        */
         .dropdown .submenu:hover > div{
          visibility:visible;
           opacity:1;
        }
        
          .dropdown:hover > div{
            visibility:visible;
            opacity:1;
          }
        
          .dropdown a{
            display:block;
            text-decoration:none;
            padding:8px;
            color:#000;
            transition:.1s;
            white-space:nowrap;
          }
          
          .dropdown a:hover,.dropdown .submenu:hover > a{
            background-color:mediumSeaGreen;
            color:#fff;
          }
        
    </style>
    <body>
        <div id="nav-wrapper">
            <div id="nav" class="navbar navbar-default navbar-inner">
                <div class="container ">
            
                     <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                       <span class="sr-only">Toggle navigation</span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                      </button>
                      <a href="#page-top" class="navbar-brand navbar-brand-centered"><img src="{% static 'frontend-assets/images/logo.png' %}" alt="First slide"></a>
                    </div> 
    
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="hidden">
                                <a href="#page-top"></a>
                            </li>
                            <li>
                                <a class="page-scroll first" href="{% url 'frontend:index' %}">Home</a>
                            </li>
                            <li>
    
                                <div class="dropdown">
                                    <button>Custom Trips options</button>
                                        <div>
    
                                                {% for state,j in lst %}
                                                 <div class="submenu">
                                                    <a href="{% url 'frontend:state_detail' state.id %}">{{state.title}}</a>
    
                                                     <div>
                                                            {% for district,treks in j %}	
                                                            <div class="submenu">
                                                            
                                                                <a href="{% url 'frontend:district_detail' district.id %}">{{district.title}}</a>
                                                                <div>
                                                                     {% for trek in treks %}
                                                                    <div class="submenu">
                                                                        <a href="{% url 'frontend:detail' trek.id %}">{{trek.title}}</a>
                                                                    </div>
                                                                    {% endfor %} 
                                                                </div> 
    
                                                            </div>
                                                                    
                                                            {% endfor %} 
                                                    </div> 
                                                </div>	
                                                {% endfor %}		
                                        </div>
    
                                        
                                </div>
                            </li>
    
                            {% comment %} <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                  Trips
                                </a
                                <ul class="dropdown-menu">
                                    {% for i in state %}
                                    <li><a class="dropdown-item" href="#">{{i.title}}</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    {% endfor %}
    
                                  <li>
                                    <hr class="dropdown-divider">
                                  </li>
                                  <li class="nav-item dropend">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                      Dropdown
                                    </a>
                                    <ul class="dropdown-menu">
                                      <li><a class="dropdown-item" href="#">Action</a></li>
                                      <li><a class="dropdown-item" href="#">Another action</a></li>
                                      <li>
                                        <hr class="dropdown-divider">
                                      </li>
                                      <li class="nav-item dropend">
                                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                          Dropdown
                                        </a>
                                        <ul class="dropdown-menu">
                                          <li><a class="dropdown-item" href="#">Action</a></li>
                                          <li><a class="dropdown-item" href="#">Another action</a></li>
                                          <li>
                                            <hr class="dropdown-divider">
                                          </li>
                                          <li class="nav-item dropend">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                              Dropdown
                                            </a>
                                            <ul class="dropdown-menu">
                                              <li><a class="dropdown-item" href="#">Action</a></li>
                                              <li><a class="dropdown-item" href="#">Another action</a></li>
                                              <li>
                                                <hr class="dropdown-divider">
                                              </li>
                                              <li><a class="dropdown-item" href="#">Something else here</a></li>
                                            </ul>
                                          </li>
                                        </ul>
                                      </li>
                                    </ul>
                                  </li>
                                </ul>
                            </li> {% endcomment %}
                            
                            <li>
                                <a class="page-scroll first" href="#nav-services">Services</a>
                            </li>
                            <li>
                                <a class="page-scroll" href="#nav-event">Event</a>
                            </li>
                            <li>
                                <a class="page-scroll" href="#nav-gallery">Gallery</a>
                            </li>						
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a class="page-scroll" href="#nav-adventures">Adventures</a>
                            </li>
                            <li>
                                <a class="page-scroll" href="#nav-testimonials">Testimonials</a>
                            </li>
                            <li>
                                <a class="page-scroll" href="#location">Location</a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse --> 
                
                </div> <!-- row -->
            </div> <!-- nav --> 
        </div>