accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/',Signup, name='signup'),
    path('login/', Login, name='login'),
    path('logout/', Logout, name='logout')
]

frontend/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'frontend'

urlpatterns = [
    path('', index, name='index'),
    path('detail/<int:id>/', TrekDetail, name='detail'),
    #banner
    path('banners/', BannerImages, name='banner'),
    path('add-banner/', AddBannerImages, name='add_banner'),
    path('view-banner/<int:id>/', ViewBanners, name='view_banner'),
    path('edit-banner/<int:id>/', EditBanner, name='edit_banner'),
    path('delete-banner/<int:id>/', DeleteBanner, name='delete_banner'),
    path('activate-deactive-banner/<int:id>/', ActivatDeactivateBanner, name='activate_deactivate_banner'),
    #State
    path('state-list/',StateList, name='state_list'),
    path('state-detail/<int:id>/',StateDetail, name='state_detail'),
    path('add-state/', AddState, name='add_state'),
    path('view-state/<int:id>/', ViewState, name='view_state'),
    path('edit-state/<int:id>/', EditState, name='edit_state'),
    path('delete-state/<int:id>/', DeleteState, name='delete_state'),
    path('activate-deactivate-state/<int:id>/', ActivatDeactivateState, name='activate_deactivate_state'),

    #district
    path('district-list/',DistrictList, name='district_list'),
    path('district-detail/<int:id>/',DistrictDetail, name='district_detail'),
    path('add-district/', AddDistrict, name='add_district'),
    path('view-district/<int:id>/', ViewDistrict, name='view_district'),
    path('edit-district/<int:id>/', EditDistrict, name='edit_district'),
    path('delete-district/<int:id>/', DeleteDistrict, name='delete_district'),
    #Tresks
    path('trek-list/',TrekList, name='trek_list'),
    path('add-trek/', AddTrek, name='add_trek'),
    path('view-trek/<int:id>/', ViewTrek, name='view_trek'),
    path('edit-trek/<int:id>/', EditTrek, name='edit_trek'),
    path('delete-trek/<int:id>/', DeleteTrek, name='delete_trek'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  url
from accounts.views import AdminLoginView


urlpatterns = [
    url(r'^admin/login/', AdminLoginView.as_view()),
    # path('index/', index, name='index'),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls',namespace='user')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    # path('store/', include('store.urls',namespace='store')),
    path('', include('frontend.urls',namespace='frontend')),
    path('loggers/', include('logger.urls',namespace='loggers')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

app_name = 'users'

urlpatterns = [
    path('users-list/', UserList, name='users_list'),
]

templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                <a target="_blank" 
                   href="https://appseed.us/admin-dashboards/django" 
                   class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
               &copy; <a target="_blank" 
                         href="https://bit.ly/3fKQZaL">Creative-Tim</a> 
               - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a href="https://appseed.us/admin-dashboards/django" 
                 class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="https://bit.ly/3fKQZaL" 
                 class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a> 
                 - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </footer>

templates/includes/navigation-fullscreen.html
{% load static %}
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="{% static 'assets/img/brand/white.png' %}" alt="Argon Design - Template Starter Logo.">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="{% static 'assets/img/brand/blue.png' %}">
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="{% url 'accounts:login' %}" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'accounts:signup' %}" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
        </li>
      </ul>
      <hr class="d-lg-none" />
      <ul class="navbar-nav align-items-lg-center ml-lg-auto">
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.facebook.com/webappseed" 
             target="_blank" data-toggle="tooltip" data-original-title="Like us on Facebook">
            <i class="fab fa-facebook-square"></i>
            <span class="nav-link-inner--text d-lg-none">Facebook</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://twitter.com/webappseed" 
             target="_blank" data-toggle="tooltip" data-original-title="Follow us on Twitter">
            <i class="fab fa-twitter-square"></i>
            <span class="nav-link-inner--text d-lg-none">Twitter</span>
          </a>
        </li>
        <li class="nav-item d-none d-lg-block ml-lg-4">
          <a href="https://appseed.us/admin-dashboards/django-dashboard-argon-pro" 
             target="_blank" class="btn btn-neutral btn-icon">
            <span class="btn-inner--icon">
              <i class="fas fa-rocket mr-2"></i>
            </span>
            <span class="nav-link-inner--text">PRO Version</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
      <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
        <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input class="form-control" placeholder="Search" type="text">
          </div>
        </div>
        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </form>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
            <!-- Dropdown header -->
            <div class="px-3 py-3">
              <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">13</strong> notifications.</h6>
            </div>
            
            <!-- List group -->
            <div class="list-group list-group-flush">
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-1.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-2.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>3 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-3.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>5 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Your posts have been liked a lot.</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-5.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>3 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
                  </div>
                </div>
              </a>
            </div>

            <!-- View all -->
            <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
          </div>
        </li>


        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-ungroup"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">
            <div class="row shortcuts px-4">
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                  <i class="ni ni-calendar-grid-58"></i>
                </span>
                <small>Calendar</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                  <i class="ni ni-email-83"></i>
                </span>
                <small>Email</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                  <i class="ni ni-credit-card"></i>
                </span>
                <small>Payments</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-green">
                  <i class="ni ni-books"></i>
                </span>
                <small>Reports</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
                  <i class="ni ni-pin-3"></i>
                </span>
                <small>Maps</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-yellow">
                  <i class="ni ni-basket"></i>
                </span>
                <small>Shop</small>
              </a>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            {% comment %} <a target="_blank" href="http://appseed.us/support" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a> {% endcomment %}
            <div class="dropdown-divider"></div>
            <a href="" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/scripts.html
  {% load static %}
  
  <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
  {% comment %} <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script> {% endcomment %}
  <script src="/static/admin/js/validate.js"></script>

templates/includes/sidenav.html
{% load static %}

<style>
  .active{
    color:black ! important
  }
</style>

<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      {% comment %} <h1>Jalpa Medical</h1> {% endcomment %}
      <a class="navbar-brand" href="{% url 'frontend:index' %}">
        <h1 style="color:#5e72e4">Jalpa Medical</h1>
        {% comment %} <img src="{% static 'assets/img/brand/blue.png' %}" class="navbar-brand-img" alt="Argon Design - Jinja Template Logo."> {% endcomment %}
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if not head_title %} active {% else %} {% endif %}" href="{% url 'frontend:index' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Dashboard</span>
            </a>
          </li>
          <li data-toggle="tooltip" title="Add Your Project!" class="nav-item">
            <a class="nav-link {% if head_title == 'Pharmacy_Management' %} active {% else %} {% endif %}" href="{% url 'store:add_pharmacy' %}">
              <i class="fa-solid fa-house-medical-flag text-blue"></i>         
              <span class="nav-link-text">Pharmacy</span>
            </a>
          </li>
          <li data-toggle="tooltip" title="Add Your Worker!" class="nav-item">
            <a class="nav-link {% if 'worker' in segment %} active {% endif %}" href="">
              <span class="nav-link-text ">Store</span>
            </a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link {% if 'attendence' in segment %} active {% endif %}" href="{% url 'add_attendance' %}">
              <i class="ni ni-bullet-list-67 text-default"></i>
              <span class="nav-link-text">Attendance</span>
            </a>
          </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link {% if head_title == 'Category_Management'%}% active {% endif %}" href="{% url 'store:add_category' %}">
              <i class="ni ni-chart-pie-35 text-blue"></i>
              <span class="nav-link-text ">Category</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if head_title == 'Product_Management' %} active {% endif %}" href="{% url 'store:product_listing' %}">
              <i class="fa-brands fa-product-hunt text-blue"></i>
              <span class="nav-link-text">Product</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if head_title == 'Stock_Management' %} active {% endif %}" href="{% url 'store:stock_listing' %}">
              <i class="fa-solid fa-capsules text-blue"></i>          
              <span class="nav-link-text">Stock</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if head_title == 'Customer_Management' %} active {% endif %}" href="{% url 'store:customer_listing' %}">
              <i class="fa-solid fa-hospital-user text-blue"></i>
              <span class="nav-link-text">Customer</span>
            </a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:payu' %}">
              <i class="ni ni-single-02 text-yellow"></i>
              <span class="nav-link-text">payu</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="ni ni-single-02 text-yellow"></i>
              <span class="nav-link-text">pdf</span>
            </a>
          </li> {% endcomment %}


          {% comment %} <li class="nav-item">
            <a class="nav-link {% if 'user:contact' in segment %} active {% endif %}" href="">
              <i class="ni ni-box-2"></i>
              <span class="nav-link-text">Contacts</span>
            </a>
          </li> 
          <li class="nav-item">
            <a class="nav-link {% if 'user:classes' in segment %} active {% endif %}" href="">
              <i class="ni ni-album-2"></i>
              <span class="nav-link-text ">Classes</span>
            </a>
          </li> {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link {% if 'tables' in segment %} active {% endif %}" href="#">
              <i class="ni ni-bullet-list-67 text-default"></i>
              <span class="nav-link-text">Tables</span>
            </a>
          </li> {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="/login.html">
              <i class="ni ni-key-25 text-info"></i>
              <span class="nav-link-text">Login (template)</span>
            </a>
          </li> {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="/register.html">
              <i class="ni ni-circle-08 text-pink"></i>
              <span class="nav-link-text">Register (template)</span>
            </a>
          </li> {% endcomment %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:logout' %}">
              <i class="ni ni-user-run text-red text-blue"></i>
              <span class="nav-link-text">Logout</span>
            </a>
          </li>            
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        {% comment %} <h6 class="navbar-heading p-0 text-muted">
          <span class="docs-normal">Resources</span>
        </h6> {% endcomment %}
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">

          {% comment %} <li class="nav-item">
            <a class="nav-link" 
               target="_blank" 
               href="https://appseed.us/admin-dashboards/django-dashboard-argon">
              <i class="ni ni-archive-2"></i>
              <span class="nav-link-text">Product Page</span>
            </a>
          </li> {% endcomment %}

          {% comment %} <li class="nav-item">
            <a class="nav-link" 
               target="_blank" 
               href="https://appseed.us/admin-dashboards/django-dashboard-argon-pro">
              <i class="ni ni-spaceship text-red"></i>
              <span class="nav-link-text text-red">PRO Version</span>
            </a>
          </li> {% endcomment %}

          {% comment %} <li class="nav-item">
            <a class="nav-link active active-pro" 
               target="_blank" 
               href="http://appseed.us">
              <i class="ni ni-send text-dark"></i>
              <span class="nav-link-text">AppSeed</span>
            </a>
          </li> {% endcomment %}
        </ul>
      </div>
    </div>
  </div>
</nav>